companyBlog/models.py
from companyBlog import db,login_manager
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from datetime import datetime


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)


class User(db.Model,UserMixin):
    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key= True)
    profile_image = db.Column(db.String(64),nullable = False,default = 'default_profile.png')
    email = db.Column(db.String(64),unique =True,index =True)
    username = db.Column(db.String(64),unique = True,index=True)
    password_hash = db.Column(db.String(128))

    posts = db.relationship('BlogPost',backref='author',lazy=True)

    def __init__(self,email,username,password):
        self.email  =email
        self.username = username
        self.password_hash = generate_password_hash(password)

    def check_password(self,password):
        return check_password_hash(self.password_hash,password)

    def __repr__(self):
        return f"Username {self.username}"




class BlogPost(db.Model):

    users = db.relationship(User)

    id = db.Column(db.Integer,primary_key=True)

    user_id = db.Column(db.Integer,db.ForeignKey('users.id'),nullable=False)

    date = db.Column(db.DateTime,nullable=False,default=datetime.utcnow)

    title = db.Column(db.String(140),nullable=False)

    text = db.Column(db.Text , nullable=False)

    def __init__(self,title,text,user_id):
        self.title= title
        self.text = text
        self.user_id = user_id

    def __repr__(self):
        return f"Post ID: {self.id}-- Date: {self.date} --- {self.title}"

companyBlog/blog_posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField,TextAreaField
from wtforms.validators import DataRequired

class BlogPostForm(FlaskForm):
    title = StringField('Title',validators=[DataRequired()])
    text = TextAreaField('Text',validators=[DataRequired()])
    submit = SubmitField("Post")

companyBlog/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager


app = Flask(__name__)

app.config['SECRET_KEY'] = 'mysecret'
######################
## Database setup ########

basedir = os.path.abspath(os.path.dirname(__file__))
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///'+os.path.join(basedir,'data.sqlite')
app.config['SQLALCHEMY_TRACK_MODIFICATION'] = False

db = SQLAlchemy(app)
Migrate(app,db)


#############end#####################


############login configration###########

login_manager = LoginManager()

login_manager.init_app(app)
login_manager.login_view = 'users.login'

###################end#################







from companyBlog.core.views import core
from companyBlog.users.view import users
from companyBlog.blog_posts.view import blog_posts
from companyBlog.error_pages.handlers import error_pages

app.register_blueprint(core)
app.register_blueprint(users)
app.register_blueprint(blog_posts)
app.register_blueprint(error_pages)

companyBlog/core/views.py
from companyBlog.models import BlogPost
from flask import render_template,request,Blueprint

core = Blueprint('core',__name__)

@core.route('/')
def index():
    page = request.args.get('page',1,type=int)
    blog_posts = BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page,per_page=5)
    return render_template('index.html',blog_posts=blog_posts)


@core.route('/info')
def info():
    return render_template('info.html')

companyBlog/templates/account.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <div align='center'>
    <h1>Welcome to the page for {{current_user.username}}</h1>
    <img align='center' src="{{url_for('static',filename='profile_pics/'+current_user.profile_image)}}">
    </div>
  </div>
  <div class="container">
    <form class=""  method="POST" action="" enctype="multipart/form-data">
      {{form.hidden_tag()}}
       <div class="form-group">
         {{form.username.label(class='form-group')}}{{form.username(class='form-control')}}
       </div>

      <div class="form-group">
      {{form.email.label(class='form-group')}}{{form.email(class='form-control')}}
         </div>
       <div class="form-group">
      {{form.picture.label(class='form-group')}}{{form.picture(class='form-control')}}
         </div>

      <div class="form-group">
      {{form.submit(class='btn btn-primary')}}
         </div>




    </form>

  </div>

{% endblock %}

companyBlog/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>

  <link rel="stylesheet"  type= "text/css" href= "{{ url_for('static',filename='styles/mainpage.css') }}">
  <link rel="stylesheet"  type= "text/css" href= "{{ url_for('static',filename='styles/login.css') }}">

    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
<link rel="stylesheet" href=
"https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src=
"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js">
    </script>
    <script src=
"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js">
    </script>
    <script src=
"https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js">
    </script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid col">
    <img src="../static/logo.jpg" class="img_fun">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav navbar-nav ml-auto">

        <a class="nav-link active" href="{{url_for('core.index')}}">Home</a>
        {% if current_user.is_authenticated %}
        <a class="nav-link" href="{{url_for('blog_posts.create_post')}}">Post</a>
        <a class="nav-link" href="{{url_for('users.logout')}}">Logout</a>
        <a class="nav-link" href="{{url_for('users.account')}}">Account</a>
        {% else %}
        <a class="nav-link" href="{{url_for('users.login')}}">Login</a>
        <a class="nav-link" href="{{url_for('users.register')}}">Register</a>
        {% endif %}
        <a class="nav-link" href="{{url_for('core.info')}}">About</a>


      </div>
    </div>
  </div>

</nav>
<div class="container">
  {% block content %}

  {% endblock %}
</div>

  </body>
</html>

companyBlog/templates/blog_post.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <h1>{{ post.title }}</h1>
  <h2>Written by: {{post.author.username}}</h2>
  <h3>Published: {{ post.date.strftime('%B %d, %Y') }}</h3>
  <p>{{post.text}}</p>
   {% if post.author == current_user %}
     <div>
       <a class="btn btn-secondary" href="{{ url_for('blog_posts.update', blog_post_id=post.id) }}">Update</a>
       <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#del_modal">Delete</button>
     </div>
   {% endif %}
</div>




  <!-- Modal for Pop Up-->
  {# https://getbootstrap.com/docs/4.1/components/modal/ #}
  {# Notice how the link with the id to the button above! #}
  <div class="modal" tabindex="-1" role="dialog" id="del_modal">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Delete Post</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Are you sure you want to delete this blog post?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>

          <form action="{{ url_for('blog_posts.delete_post', blog_post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

companyBlog/templates/create_post.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <form class="form-group" method="POST">
     {{ form.hidden_tag() }}

     <div class="form-group">
     {{ form.title.label(class="form-control-label") }}
     {{ form.title(class="form-control form-control-lg ") }}
     </div>
     <div class="form-group">
     {{ form.text.label(class="form-control-label") }}
     {{ form.text(class="form-control form-control-lg") }}
     </div>
     <div class="form-group">
         {{ form.submit(class="btn btn-outline-info") }}
     </div>
  </form>

</div>

{% endblock content %}

companyBlog/templates/index.html
{% extends "base.html" %}
{% block content %}
  <div class="jumbotron">
    <h1> Company Blog</h1>
  </div>

  <div class="container">
    {% for post in blog_posts.items %}
    <div class="card">
      <div class="card-body">
        <h2> <a class="card-title" href="{{url_for('blog_posts.blog_post',blog_post_id=post.id)}}">{{post.title}}</a></h2><br>
        <h3><a href="{{url_for('users.user_posts',username=post.author.username)}}">written By: {{post.author.username}}</a></h3>
        <p>{{post.text[:200]}}  <br>  Published On: {{post.date.strftime('%d-%m-%Y')}}</p>
        <a class="btn btn-primary" href="{{url_for('blog_posts.blog_post',blog_post_id=post.id)}}">Read Blog</a>
      </div>

    </div>
    {% endfor %}
  </div>

  <nav aria-label='Page Navigation example'>
    <ul class="pagination justify-content-center">
      {% for page_num in blog_posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}
        {% if blog_posts.page == page_num %}
        <li class="page-item disabled">
          <a class="page-link" href="{{url_for('core.index',page= page_num)}}">{{page_num}}</a>
        </li>
        {% else %}
        <li class="page-item">
          <a class="page-link" href="{{url_for('core.index',page= page_num)}}">{{page_num}}</a>
        </li>
        {% endif %}
        {% endfor %}

      </ul>
  </nav>
{% endblock %}

companyBlog/templates/info.html
{% extends "base.html" %}
{% block content  %}
<div class="jumbotron">
  <h1>This is abhishek comapny </h1>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

</div>
{% endblock %}

companyBlog/templates/login.html
{% extends "base.html" %}
{% block content %}


  <div class="white-bg center modal-content">

    <div class="container">
  <form method="POST">
    {{form.hidden_tag()}}
    <div class="form-group">
    {{form.email.label(class='form-group font-weight-bold text-primary')}}{{form.email(class='form-control')}}
     </div>
    <div class="form-group">
    {{form.password.label(class='form-group font-weight-bold text-primary')}}{{form.password(class='form-control')}}
     </div>
    <div class="form-group" align="center">
    {{form.submit(class='btn btn-primary')}}
    </div>
  </form>



  </div>
  </div>
{% endblock %}

companyBlog/templates/register.html
{%extends "base.html" %}
{%  block content  %}

  <div class="container">


 <form  method="post">
  {{form.hidden_tag()}}
  <div class="form-group">
    {{form.email.label(class='form-group font-weight-bold text-success')}}{{form.email(class='form-control')}}
    </div>
  <div class="form-group">
    {{form.username.label(class='form-group font-weight-bold text-success')}}{{form.username(class='form-control')}}
  </div>
  <div class="form-group">
    {{form.password.label(class='form-group font-weight-bold text-success')}}{{form.password(class='form-control')}}
  </div>
  <div class="form-group">
    {{form.pass_confirm.label(class='form-group font-weight-bold text-success')}}{{form.pass_confirm(class='form-control')}}
  </div>
  <div class="form-group" align="center">
    {{form.submit(class='btn btn-primary')}}
  </div>


</form>
</div>

{% endblock %}

companyBlog/templates/user_blog_posts.html
{% extends "base.html"  %}
{% block content %}

<div class="container">
  <div class="jumbotron">
    <div align="center">
      <h1>welcome to the page for {{user.username}}</h1>
      <img src="{{url_for('static',filename='profile_pics/'+user.profile_image)}}">

    </div>

  </div>


{% for post in blog_posts.items %}
 <h2><a href="{{url_for('blog_posts.blog_post',blog_post_id=post.id)}}">{{post.title}}</a></h2>
 Written By: <a href="{{url_for('users.user_posts',username=post.author.username)}}">{{post.author.username}}</a>
 <p class="text-muted">Published on: {{post.date.strftime("%y-%m-%d")}}</p>
 <br>
 <p>{{post.text}}</p>
 <br>
{% endfor %}
</div>

<nav aria-label='Page Navigation example'>
  <ul class="pagination justify-content-center">
    {% for page_num in blog_posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}
      {% if blog_posts.page == page_num %}
      <li class="page-item disabled">
        <a class="page-link" href="{{url_for('users.user_posts',username=user.username,page= page_num)}}">{{page_num}}</a>
      </li>
      {% else %}
      <li class="page-item">
        <a class="page-link" href="{{url_for('users.user_posts',username=user.username,page= page_num)}}">{{page_num}}</a>
      </li>
      {% endif %}
      {% endfor %}

    </ul>
</nav>
{% endblock %}